import hashlib
from pathlib import Path
from typing import Dict, List, Any, Tuple
from datetime import datetime, timezone

class CodeBuilder:
    def __init__(self, workspace_root: str):
        if not workspace_root:
            raise ValueError("CodeBuilder: workspace_root가 명시되어야 합니다.")
        self.workspace_root = Path(workspace_root)
        self.workspace_root.mkdir(parents=True, exist_ok=True)
    
    def run(self, state: Dict[str, Any], extracted_files: List[Dict[str, str]]) -> Tuple[Dict[str, Any], List[bool]]:
        """
        [전면 재설계된 헤드리스 빌더]
        에이전트가 추출한 {"file_path": "...", "code": "..."} 배열을 받아
        원자적으로 디스크에 쓰고 file_index를 업데이트합니다.
        """
        results = []
        for file_info in extracted_files:
            file_path = file_info.get("file_path")
            code_content = file_info.get("code")
            
            if not file_path or not code_content:
                continue
                
            full_path = self.workspace_root / file_path
            success = self._atomic_write(full_path, code_content)
            results.append(success)
            
            if success:
                self._update_file_index(state, str(full_path), code_content)
                
        # 파일이 단 한 개라도 쓰였다면 성공으로 간주 (문법 검사는 Execution에서 컷팅 완료됨)
        state["build_status"] = "success" if any(results) else "failed"
        if state["build_status"] == "failed":
             state["build_error_log"] = " CodeBuilder: 파일 시스템 쓰기 실패 또는 유효한 파일 데이터가 없습니다."
        else:
             state["build_error_log"] = ""
             
        return state, results

    def _atomic_write(self, full_path: Path, new_code: str) -> bool:
        full_path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = full_path.with_suffix(full_path.suffix + ".tmp")
        
        try:
            tmp_path.write_text(new_code, encoding="utf-8")
            tmp_path.replace(full_path)
            return True
        except Exception as e:
            print(f"⚠️ [Atomic Writer] 파일 실물 저장 실패 ({full_path.name}): {e}")
            if tmp_path.exists():
                tmp_path.unlink()
            return False

    def _update_file_index(self, state: Dict[str, Any], file_path: str, content: str):
        if "file_index" not in state:
            state["file_index"] = {}
            
        try:
            rel_path = str(Path(file_path).relative_to(self.workspace_root)).replace("\\", "/")
        except ValueError:
            rel_path = Path(file_path).name

        file_hash = hashlib.md5(content.encode('utf-8')).hexdigest()

        if rel_path not in state["file_index"]:
            state["file_index"][rel_path] = {
                "path": rel_path,
                "last_modified_agent": "Developer",
                "last_modified_task": state.get("current_sprint_task_id", "unknown"),
                "last_modified_at": datetime.now(timezone.utc).isoformat(),
                "change_summary": "Auto-generated by pipeline",
                "purpose": "Component implementation",
                "last_hash": file_hash,
                "dependencies": []
            }
        else:
            meta = state["file_index"][rel_path]
            meta["last_modified_agent"] = "Developer"
            meta["last_modified_at"] = datetime.now(timezone.utc).isoformat()
            meta["last_modified_task"] = state.get("current_sprint_task_id", "unknown")
            meta["last_hash"] = file_hash