(() => {
  "use strict";
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const meta = {
    delivery: {context:"사용자에게 전달",title:"검증된 앱과 필요한 역할만 다음 사용자에게 전달합니다.",description:"플랫폼 권한을 상속하고 수신자가 승인한 뒤에만 앱이 활성화됩니다.",jarvisContext:"CURRENT CONTEXT · 앱 전달",jarvisTitle:"물류 담당자에게 필요한 입력 권한만 제안했습니다.",jarvisText:"계약단가와 공급사 평가정보는 제외하고 통관·입항·이동 상태 4개 필드만 공유합니다."},
    inbox: {context:"받은 앱·내 앱",title:"업무를 이어받아<br>내 앱으로 사용합니다.",description:"전달 목적과 권한을 확인하고 승인한 앱만 내 업무 공간에 등록됩니다.",jarvisContext:"CURRENT CONTEXT · 받은 앱",jarvisTitle:"승인 전에 내 책임과 데이터 범위를 먼저 확인하세요.",jarvisText:"이 요청은 물류 상태 4개 필드만 수정하며 계약단가에는 접근하지 않습니다."},
    decision: {context:"의사결정 센터",title:"시뮬레이션을<br>실행 결정으로 바꿉니다.",description:"요청자·의사결정자·영향부서가 같은 근거를 각자의 관점에서 검토합니다.",jarvisContext:"CURRENT CONTEXT · DP-2026-014",jarvisTitle:"권고안은 이익 방어와 납기 위험의 균형점에 있습니다.",jarvisText:"Option A는 현금 유출을 14.2억 줄이면서 납기 준수율을 96.8%로 유지합니다."},
    publication: {context:"보고서 발간",title:"회사 전망을<br>신뢰 가능한 문서로 냅니다.",description:"대내 보고와 대외 발간을 분리하고 근거·민감정보·승인 게이트를 통과시킵니다.",jarvisContext:"CURRENT CONTEXT · 하반기 경영전망",jarvisTitle:"내부용은 준비됐고, 외부 발간은 책임자 승인이 필요합니다.",jarvisText:"외부용으로 전환하면 계약단가를 제거하고 예측 수치에 가정 범위와 기준일을 표시합니다."}
  };
  let toastTimer;
  function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2600)}
  function route(name,push=true){if(!meta[name])name="inbox";$$('[data-screen]').forEach(el=>el.classList.toggle('active',el.dataset.screen===name));$$('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===name));const m=meta[name];$("#pageContext").textContent=m.context;$("#moduleTitle").innerHTML=m.title;$("#moduleDescription").textContent=m.description;$("#jarvisContext").textContent=m.jarvisContext;$("#jarvisTitle").textContent=m.jarvisTitle;$("#jarvisText").textContent=m.jarvisText;if(push&&location.hash!==`#${name}`)history.pushState(null,"",`#${name}`);window.scrollTo(0,0)}
  $$('[data-route]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();route(button.dataset.route)}));
  window.addEventListener('hashchange',()=>route(location.hash.slice(1),false));
  $("#sendDelivery").addEventListener('click',()=>{const selected=$$('.person input:checked').length;if(!selected){toast('전달할 사용자를 한 명 이상 선택해 주세요.');return}$("#sendDelivery").textContent=`전달 요청 완료 · ${selected}명 확인 대기`;$("#sendDelivery").style.background="#138578";$("#sendDelivery").style.borderColor="#138578";toast(`${selected}명에게 역할·권한이 포함된 앱 전달 요청을 보냈습니다.`)});
  $$('.person input').forEach(input=>input.addEventListener('change',()=>input.closest('.person').classList.toggle('selected',input.checked)));
  $("#acceptApp").addEventListener('click',()=>{const request=$("#primaryRequest");request.innerHTML='<div class="request-top"><span class="app-mark">RM</span><div><small>승인 완료 · 방금</small><h3>원료도입계획 & 추적 Workbench</h3><p>내 앱에 등록되었습니다. 담당 원료 12건의 상태 입력을 시작할 수 있습니다.</p></div><button class="primary-button">앱 열기</button></div>';request.classList.remove('active');$("#pendingMetric").textContent='1';$("#myAppMetric").textContent='7';$("#inboxCount").textContent='1';$("#appPocket").insertAdjacentHTML('afterbegin','<button><i class="blue">RM</i><span><b>원료도입계획 & 추적</b><small>신규 · 할 일 12</small></span><em>열기</em></button>');toast('승인했습니다. 플랫폼 권한을 적용해 내 앱에 등록했습니다.')},{once:true});
  $("#rejectApp").addEventListener('click',()=>toast('거절 사유를 작성해 전달자에게 회신하는 단계입니다.'));
  $$('.view-tabs button').forEach(button=>button.addEventListener('click',()=>{$$('.view-tabs button').forEach(el=>el.classList.toggle('active',el===button));$$('[data-role-view]').forEach(el=>el.classList.toggle('active',el.dataset.roleView===button.dataset.view))}));
  $("#requestMeeting").addEventListener('click',()=>{$("#requestMeeting").textContent='회의 요청 완료 · 참석자 확인 대기';$("#requestMeeting").style.background='#138578';$("#requestMeeting").style.borderColor='#138578';$("#decisionState").textContent='8월 5일 10:30 · 참석 확인 중';$("#decisionState").className='state-chip success';toast('역할별 검토서 3종을 첨부해 의사결정 회의를 요청했습니다.')},{once:true});
  let approvalReady=false;
  let legalReady=false;
  let publicationAudience='internal';
  function updatePublicationGate(){const external=publicationAudience==='external';const readyCount=2+(approvalReady?1:0)+(external&&legalReady?1:0);const required=external?4:3;$('#gateProgress').textContent=`${readyCount} / ${required} 준비`;const publish=$('#publishReport');const canPublish=approvalReady&&(!external||legalReady);publish.disabled=!canPublish;publish.classList.toggle('disabled',!canPublish);publish.textContent=canPublish?(external?'대외 보고서 발간':'대내 경영보고 발간'):(external?'책임자·법무 승인 후 발간':'책임자 승인 후 발간')}
  window.switchPublicationAudience=(audience,button)=>{$$('.audience-tabs button').forEach(el=>el.classList.toggle('active',el===button));$$('[data-audience-panel]').forEach(el=>el.classList.toggle('active',el.dataset.audiencePanel===audience));publicationAudience=audience;$('.publish-console').classList.toggle('external-mode',publicationAudience==='external');updatePublicationGate();if(publicationAudience==='external')toast('대외 발간 정책을 적용했습니다. 법무·공시 검토가 추가됩니다.')};
  $("#approvalGate").addEventListener('click',()=>{const gate=$("#approvalGate");approvalReady=true;gate.classList.add('ready');gate.querySelector('i').textContent='✓';gate.querySelector('small').textContent='최영수 상무 승인 완료 · 방금';gate.querySelector('em').textContent='완료';updatePublicationGate();toast(publicationAudience==='external'?'책임자 승인이 반영됐습니다. 법무·공시 검토가 남았습니다.':'책임자 승인이 반영되어 발간할 수 있습니다.')},{once:true});
  $("#legalGate").addEventListener('click',()=>{const gate=$("#legalGate");legalReady=true;gate.classList.add('ready');gate.querySelector('i').textContent='✓';gate.querySelector('small').textContent='법무·공시 검토 완료 · 방금';gate.querySelector('em').textContent='완료';updatePublicationGate();toast('법무·공시 검토가 완료되어 대외 발간할 수 있습니다.')},{once:true});
  $("#publishReport").addEventListener('click',()=>{if($("#publishReport").disabled)return;$("#publishReport").textContent='발간 완료 · 배포 추적 시작';$("#publishReport").style.background='#138578';$("#publishReport").style.borderColor='#138578';$("#publishState").textContent='PUBLISHED';toast('승인된 수신자에게 보고서를 발간하고 열람 추적을 시작했습니다.')},{once:true});
  $$('.format-row button').forEach(button=>button.addEventListener('click',()=>{$$('.format-row button').forEach(el=>el.classList.toggle('selected',el===button));toast(`${button.textContent} 형식을 선택했습니다.`)}));
  const answers={"이 앱을 승인하면 내가 해야 할 일을 설명해줘":"담당 원료 12건의 통관·입항·내륙운송 상태를 갱신하게 됩니다. 입력한 값은 구매팀 도입계획과 재고 시뮬레이션에 즉시 반영됩니다.","권한과 데이터 노출 범위를 설명해줘":"사용자에게는 4개 물류 상태 필드의 읽기·쓰기만 부여됩니다. 계약단가, 공급사 평가, 타 사업부 데이터는 계속 차단됩니다.","다음 업무 흐름과 연결 관계를 설명해줘":"물류 상태 입력 → 구매 도입예정일 갱신 → 생산 재고 시뮬레이션 재계산 → 기준 초과 시 의사결정 패키지 생성 순서로 이어집니다."};
  $$('.jarvis-quick button').forEach(button=>button.addEventListener('click',()=>{$('#jarvisAnswer').textContent=answers[button.dataset.prompt]||meta[(location.hash||'#inbox').slice(1)].jarvisText}));
  $("#askJarvis").addEventListener('click',()=>{const q=$("#jarvisQuestion").value.trim();if(!q){toast('질문을 입력해 주세요.');return}$("#jarvisAnswer").textContent=`“${q}”에 대해 현재 회사 범위, 앱 권한, 의사결정 근거를 함께 확인했습니다. 이 샘플에서는 화면별 권고 답변으로 연결됩니다.`;$("#jarvisQuestion").value=''});
  route(location.hash.slice(1)||'inbox',false);
})();
